### ISSUE TITLE
Checklist 

### ISSUE THREAD

**Issue by Rafaelmoraes05** [Rafaelmoraes05/GCMS-Rafael-Moraes#2]
@ramidedantas 

- [x]  Instalar git localmente
- [ ] Criar projeto local 
- [ ] Criar repositório local e realizar commits 
- [ ] Subir alterações para o repositório remoto 
- [ ] Fazer alterações no repositórui da turma
